# Generated by Django 3.1.4 on 2022-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=255)),
                ('itemimages', models.CharField(max_length=255)),
                ('Itemcategory', models.CharField(max_length=50)),
                ('Itemdescription', models.CharField(max_length=1500)),
                ('Dateposted', models.DateField()),
                ('Itemprice', models.IntegerField()),
                ('Itemstatus', models.CharField(max_length=50)),
                ('Dateofremoval', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Phno', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=15)),
                ('cpwd', models.CharField(max_length=15)),
            ],
        ),
    ]
